### ISSUE TITLE
Docs team leader Application: Adrian Zatreanu

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/teams#1]
# Bio

Who are you? What makes you special?

I'm Adrian and I try to be funny. I also refactored the whole documentation and moved it out of the coala core, and I'm probably one of the people that knows most about the repository.

# coala Contributions so far

What contributions, coding or not, have you done to coala?
A lot of bears, cib, lots of documentation as well, some requirement classes.

# Road to the Future

How do you plan to take forward coala as a team leader of your team? What changes will you make happen?

I will coordinate in a way that hopefully no duplicate stuff will happen in the docs.
A project with good docs is a project that attracts more contributors and users in general :)

**Comment by sils** [comment]
@Adrianzatreanu would you be able/willing to lead two teams? You applied for two. Is there anything special where you see the docs team to move?

**Comment by sils** [comment]
see also https://github.com/coala/teams/issues/2

**Comment by Mariatta** [comment]
> @Adrianzatreanu would you be able/willing to lead two teams?

Same question..

**Comment by Adrianzatreanu** [comment]
I applied for these teams as cib wont require as much maintanance, and I don't see anyone that could be more fit for the documentation team. Also, leading a team does not imply writing lots of code yourself, but having an idea of how docs should look and how to prevent redundancy, by having that one person (which i consider is me) that can have an overview on all docs.
