### ISSUE TITLE
Research Team Leader Application: Udayan Tandon

### ISSUE THREAD

**Issue by Udayan12167** [coala/teams#10]
# Bio

Who are you? What makes you special?

I'm Udayan Tandon. I have been a part of coala since early 2015. I have seen coala evolve from its very primitive stages to the behemoth it is now. Mostly being involved in these evolutions. I'm also fresh out of university where my main research area was Program Analysis and my work won the best thesis award as well. I have also designed the new core of coala which is under implementation right now. Hence due to my heavy involvement in a field relevant to coala I'm mostly updated on potential research and development oppurtunities. I also have experience in doing challenging and new projects which would help with the guidance of the research team. I'll always be present to guide research project as I have an idea about the commitment and work required to drive them to completion.

# coala Contributions so far

What contributions, coding or not, have you done to coala?

I have many contributions to coala with multiple feature implementations in the core frameworks and major involvement in the architectural design of coala. I've also mentored a GSoC project for coala guiding my student with his hurdles.

# Road to the Future

How do you plan to take forward coala as a team leader of your team? What changes will you make happen

coala seriously lacks the development of it's own unique bear algorithms. My first steps would be to propose the implementation of some novel static analysis research papers inside the framework of coala. Furthermore we have had our eyes on always bringing machine learning to coala which should be our focus for the projects of the next GSoC.

**Comment by sils** [comment]
@Udayan12167 do you have any concrete proposals on which measures you will implement to make this happen?

**Comment by sims1253** [comment]
Do you have long-term and/or conceptual ideas?

**Comment by Udayan12167** [comment]
I have a concrete proposal about adding a machine learning algorithm to coala. I recently did a project in my Machine Learning course to learn coding conventions in Java. This project is essentially a paper from https://arxiv.org/pdf/1402.4182.pdf. I have an extensive understanding of this paper and would like make a native coala implementation for python. I have a clear picture of how to modify the project for it to be feasible for Python and implement it within the coala framework. As the team elections are over I would like to set about drafting a proposal for this project so that either me or someone else can pick this project up. After the proposal is evaluated by you guys we can take a call wether this project can be included in the GSoC project list or needs to take longer to be developed. You can checkout my Java implementation at https://github.com/Udayan12167/AutoSuggest. I discovered this group through @sils and I find more papers that are interesting.

**Comment by Udayan12167** [comment]
Furthermore, I plan to join one of the best Research institutes in India in the Program Analysis group. I know professors there who do extensive work in static analysis. I plan to convince them to use coala for some research and possibly collaborate with them on projects. I know this has been a difficult for coala for some time now. I know a few professors on a personal level now and hence have a better audience for this sort of work I feel.
