### ISSUE TITLE
aspects Team Leader Application: Stefan Zimmermann

### ISSUE THREAD

**Issue by userzimmermann** [coala/teams#11]
# Bio

I'm the designer of aspectclasses.

# coala Contributions so far

I created aspectclasses.

# Road to the Future

I will nurture coala and bears to make full use of aspectclasses.

**Comment by sims1253** [comment]
Do you have any concrete plans how to organize, implement and nourish aspects?

**Comment by userzimmermann** [comment]
@sims1253 Yes. I already made very concrete plans during our last hackathon in Cuxhaven. We can further discuss this now if you like. It should work over a distance of ~2m :)
