### ISSUE TITLE
core Team Member Application: Lasse

### ISSUE THREAD

**Issue by sils** [coala/teams#18]
# Bio

I'm Lasse. I'm the BLD of coala. I'm special. Also I'm western, white, male and in my 20ies so I fit the profile of an open source developer pretty well.

# coala Contributions so far

Let me see... I created it like thrice. The first version sucked so I had to make a second. It sucked as well so I made a third. It still sucks :/

# Road to the Future

Helping @Makman2 and @Udayan12167 doing their stuff for the next gen bears and coala.io/cep5 of which I'm the author. I'll help reviewing, hopefully not too much organizing, and a tiny bit of coding where possible but no big core things in the near future.

**Comment by adtac** [comment]
Hi and welcome to the coala project. Have you taken a look at coala.io/newcomer? Just kidding :D

How do I formally accept this?

**Comment by sims1253** [comment]
you kiss the bride

**Comment by sils** [comment]
@adtac nobody knows I guess, not even @sims1253 and now we catched him and he's trying to talk himself out of this

**Comment by sims1253** [comment]
the cEP covers this ;)

**Comment by adtac** [comment]
ack :)

**Comment by sims1253** [comment]
I'd love to see concrete responsibilities taken soooo
@sils what would you like to be responsible for?

**Comment by sils** [comment]
@sims1253 there are no responsibilities defined by the team lead

**Comment by Mariatta** [comment]
I approve this application.

**Comment by adtac** [comment]
@sils I don't have any particular set of responsibilities that you can choose from at the moment. But I'd like to suggest making radical design/architecture cEPs as your role? Like aspects. Might fit if you're looking for a less, uh, code-y contribution from now on.

**Comment by sils** [comment]
@adtac I think the team might receive better applications and work better if we had a clear roadmap with specific things to address because otherwise the membership won't mean a lot.

**Comment by adtac** [comment]
Right, I'll work something out.
