### ISSUE TITLE
community Team Application: Lasse

### ISSUE THREAD

**Issue by sils** [coala/teams#19]
# Bio

I'm Lasse. I'm the BLD of coala. I'm special. Also I'm western, white, male and in my 20ies so I fit the profile of an open source developer pretty well.

# coala Contributions so far

Let me see... I created it like thrice. The first version sucked so I had to make a second. It sucked as well so I made a third. It still sucks :/

# Road to the Future

I happen to own (or rather call it "be") a company named Viper Development. If everything goes well, we'd be likely to have some budget available for merch print and stuff and I think joining together coala and viperdev will make nice shirts. (Not that viperdev isn't sponsoring all the unbranded coala shirts and stuff as well but that's draining money on long term and isn't sustainably working for me. :/)

I also plan to help out with GSoC, GCI and I'm planning an initiative to get pupils at schools hooked for coding and open source in hamburg.

So yeah, go with the flooooow. See what happens.

**Comment by sims1253** [comment]
Your issue title does not fit the given template. How can I expect high quality work from you :D

looking at the [list so far](https://github.com/coala/teams/blob/master/community/community_ideas.md)
What are areas/specific tasks you would like to be responsible for?
If you have point to add to the list, please feel free to do so :)

**Comment by sils** [comment]
I'm already paying for the merchandise.
I'm already working with @hemangsk on the new website
I'd like to participate in the gaming events.
I'm already organizing talks and sprints and stuff but I don't (I repeat don't) wanna be responsible for it. That's the whole point isn't it? :P
I'm the owner of the hamburg code quality meetup and we should use it to make regular events.
I'll probably have to help with GSoC again.

**Comment by sims1253** [comment]
That's awesome :)
My idea of becoming members of the teams includes taking responsibilities for some aspects covered by the team. You are welcome to help without responsibilities but as a member I would like you to take responsibility :)

I vote for this and guess there will be something we can find for you officially (besides all the "I am doing it because nobody else does it" stuff we maybe find someone else for :D)

**Comment by Mixih** [comment]
ack :)
