### ISSUE TITLE
cib Team Leader Application: Adrian Zatreanu

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/teams#2]
Proposing a new team that operates with cib (the bear installation tool) as I have found myself
working alone and it was quite hard, so designing a team of members working on it would be
amazing.

I'd also like to propose myself as the team leader if this team happens.

# Bio

Who are you? What makes you special?
The creator of cib :p

# coala Contributions so far

What contributions, coding or not, have you done to coala?

I have done cib!! 

# Road to the Future

How do you plan to take forward coala as a team leader of your team? What changes will you make happen?

I plan on coordinating the team on actually revamping cib and making it usable soonish, as it may be used by many people :)

**Comment by sils** [comment]
@Adrianzatreanu how is your goal being achieved?

**Comment by Adrianzatreanu** [comment]
I already am working on it and moved the requirements to a separate repo, and @Nosferatul is already trying to help me to make it happen. we're working on distribution requirements :)
