### ISSUE TITLE
Docs Team Member application: Mariatta

### ISSUE THREAD

**Issue by Mariatta** [coala/teams#24]
# Bio

My name is Mariatta, and I'm extra super duper special because:
- At the time of applying, I'm the only woman in coala maintainers team.
- I'm on IMDb http://www.imdb.com/name/nm7641957/

Other documenting expriences:
- Improving documentation for CPython, Python.org, Python Developer's Guide.

# coala Contributions so far

- documentation
- review prs
- accept prs
- helped onboard newcomers and new contributors

# Road to the Future

- continue working on docs

**Comment by sils** [comment]
I hereby vote for this :)

**Comment by Adrianzatreanu** [comment]
ack :)

**Comment by sils** [comment]
@Mariatta can you make a PR adding yourself to the team closing this issue?

**Comment by adtac** [comment]
@Mariatta wanna make a PR adding yourself? :)
