### ISSUE TITLE
Community Member Application: Kaisar Arkhan

### ISSUE THREAD

**Issue by yukiisbored** [coala/teams#30]
# Bio

I'm (currently) a 16 years old open source programmer, I've been a Linux user since 2006 and I've been starting to taken interest in programming at the same time. I've had a ton of experience with building a community (most of them are from my experience in building and managing a game server). I'm also a weeb, I read manga every night. I rarely watch anime though. I love the hell out of *nix operating systems because they're moe. I'm currently manage networking and server stuff at my school.

# coala Contributions so far

I've created a python script to generate a `bear-requirements.txt` file the bears' metadata, I've fixed a problem with severity on XMLBear, and I've fixed a simple issue which is replacing `assertRaises` to `assertRaisesRegex`

# Road to the Future

I want to make coala into a friendly community for new / wannabe open source contributors. coala already has the base to be friendly and introduce other new programmers contributing to a FOSS project  and encourage them to make contributions.

I want to take responsibility for Developer discussions.

**Comment by sims1253** [comment]
Same question for you :)
What do you want to take responsibility for :) The more specific you get, the easier to organise and give credit to you :D
If you want to add things to the list, please do!
https://github.com/coala/teams/blob/master/community/community_ideas.md

**Comment by yukiisbored** [comment]
@sims1253 I've added it.

**Comment by sils** [comment]
Hey @yukiisbored you seem to have some experience with server administration etc., would you want to help us with that as well? Part of [Max' big list](https://github.com/coala/teams/blob/master/community/community_ideas.md) is also to get a better version of the old [coala planet](planet.coala-analyzer.org) up and running by using probably simething from [this list of tools](https://github.com/Kickball/awesome-selfhosted#feed-readers), we'd run it on [our server](solar.coala.io) and hook it up to something like planet.coala.io or blog.coala.io.

**Comment by yukiisbored** [comment]
Sure, I don't mind doing sysadmin/devops work. I actually love doing those.

**Comment by sims1253** [comment]
ack
someone from the community team wanna ack this?

**Comment by sils** [comment]
ack
