### ISSUE TITLE
Release Team Leader Application: Max Hahn

### ISSUE THREAD

**Issue by Mixih** [coala/teams#39]
# Bio

I'm Max, and I try to make masterpieces like [this](https://cloud.githubusercontent.com/assets/7521600/21007379/9af905ea-bd62-11e6-8735-fd8edcfd5c9f.png). Anyways, I've been around coala a while and generally know how things work around here. I also like putting check-marks in check-boxes so I think I would get along well with the current applicant we have to release team. (no I'm not German, it's just spelled that way)

# coala Contributions so far
>What contributions, coding or not, have you done to coala?

I've written a few patches as can be seen in my profile. I joined around the 0.9 release crunch and I started reviewing patches then. I have been regularly reviewing patches ever since. I released coala version 0.9.1 and coala-bears version 0.9.3 so I have some experience with the release process.

# Road to the Future

>How do you plan to take forward coala as a team leader/member of your team? What changes will you make happen?

I would like to automate more of the release notes/release process. One thing we have discussed already is autogenerating release notes from the issues associated with each commit. Another planned improvement is implementing the necessary things for the rultor release command to work. As part of my duties as release team leader, I plan on putting in a cEP to define release frequency and procedures.

**Comment by Mariatta** [comment]
I approve this.

**Comment by sils** [comment]
me too but I think @sims1253 has to put up a full vote for him again, right?

**Comment by sils** [comment]
according to the holy laws of coala

**Comment by sims1253** [comment]
I also approve this but we do have to put up a vote according to the cEP

**Comment by sils** [comment]
so put it up!

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by Mariatta** [comment]
Just feels tedious. Can't you veto it and just accept it :sweat_smile: ? (especially considering there is no other contenders :thinking: )

**Comment by sils** [comment]
Well legally we have nothing binding anyway, we just have the cEPs and we claim those are our rules. Generally this can be decided if more than half of the members have voted yes or we do the one week thing to give everyone a chance.

**Comment by adtac** [comment]
FWIW, I also vote for this :P

**Comment by sils** [comment]
@sims1253 ?

**Comment by sims1253** [comment]
@sils pinging me because you want me to make the election? Everyone can do that :)

**Comment by sils** [comment]
@sims1253 you know the tools and processes

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by Mariatta** [comment]
What's needed to start the voting?

**Comment by sims1253** [comment]
I'll do it.
We should think about some kind of Board where we publish election stuff so we don't have to spam everything all the time.
Or need one way to contact every maintainer.

**Comment by meetmangukiya** [comment]
> Or need one way to contact every maintainer.
 
@coala/coala-maintainers  ?

**Comment by meetmangukiya** [comment]
@Mixih is the release team leader, close this?

**Comment by userzimmermann** [comment]
@mixih Regarding:

> I would like to automate more of the release notes/release process. One thing we have discussed already is autogenerating release notes from the issues associated with each commit.

Have you heard about https://pypi.python.org/pypi/towncrier

I discovered it via `pytest` and @RonnyPfannschmidt. You can find more info here:

https://github.com/pytest-dev/pytest/pull/2431

cc @coala/coala-maintainers
