### ISSUE TITLE
Core Team Member Application: Udayan Tandon

### ISSUE THREAD

**Issue by Udayan12167** [coala/teams#42]
# Bio

I'm RTL(Research Team Lead). Have contributed to coala for two years coming up next month.

# coala Contributions so far

Many contributions to core and a failed GUI(Yes I'm owning it :P ).

# Road to the Future

Build a bridge between Research team and Core team in terms of implementations.

# Specific Responsibilities

Currently on the next gen bear design with @Makman2.

**Comment by adtac** [comment]
Approving this solely because of your GUI contributions :P

ack :)

**Comment by adtac** [comment]
@sils ack this?

**Comment by sils** [comment]
ack

**Comment by sims1253** [comment]
you can create a pr to add udayan to the team list and close this issue with it ;)

**Comment by adtac** [comment]
I'll create a PR for everyone :)

**Comment by adtac** [comment]
Or maybe everyone making a PR themselves is the best way.

In that case, why not make PRs the application method? We could just let them add the text as the PR body. Much easier IMO.
