### ISSUE TITLE
Community Team Member Application: Udayan Tandon

### ISSUE THREAD

**Issue by Udayan12167** [coala/teams#43]
# Bio

I'm RTL(Research Team Lead). Have contributed to coala for two years coming up next month.

# coala Contributions so far

Many contributions to core and a failed GUI(Yes I'm owning it :P ).

# Road to the Future

Make research a habit in coala and apply to as many outreach programs as possible.

# Specific Responsibilities

Applying for RGSoC for the next month.

**Comment by sims1253** [comment]
Do you want to take ongoing responsibilities in the community team or just manage the RGSoC application?
Becoming part of the team, in my understanding, would add a more long term determination to the community team's work.

**Comment by sims1253** [comment]
Just to clarify: Would you also admin the RGSoC? In that case the membership is a no brainer. If you just (not meant as derogatory) write the application with no further involvement, I feel like a team membership is not needed.

**Comment by Udayan12167** [comment]
Yes, I would become the primary contact for RGSoC. That was the intention. Surely I would like to take up more responsibility as well in community team. For now this is the only responsibility that comes to my mind. :D

**Comment by sims1253** [comment]
ack from me then :)

**Comment by hemangsk** [comment]
ack 👍
