### ISSUE TITLE
core Team Member Application: Rishav Kumar

### ISSUE THREAD

**Issue by aptrishu** [coala/teams#44]
# Bio

I'm Rishav, undergraduate student from India. I love algorithms.

# coala Contributions so far

I have contributed code to coala, coala-bears and coala_utils. I'm also working on Jenkins plugin of coala. I'm helping newcomers and reviewing PRs and old Issues.

# Specific Responsibilities

As I said I love algorithms so I'd like to optimize coala to enhance its performance and speed. I have also been reviewing codes of nextgen design, so I'd definitely like to help in that field as well.

**Comment by adtac** [comment]
ack :)

**Comment by adtac** [comment]
@sils do you approve this application? (one more ack needed and you're the only other member)

**Comment by sils** [comment]
ack

**Comment by Mariatta** [comment]
ack

**Comment by adtac** [comment]
Merged
