### ISSUE TITLE
Core Team Member Application: Rohan VB

### ISSUE THREAD

**Issue by RohanVB** [coala/teams#46]
# Bio

I'm Rohan. I'm currently a 3rd year undergrad student of Maths & Computing in India.

# coala Contributions so far

My main contributions have been to the coala/coala repo, solving and opening issues. I've also reviewed a few PRs in the same repo. Other contributions have been in the coala/documentation repo. 

# Road to the Future

I think reviewing PRs and helping newcomers get adjusted to the coala workflow is extremely important. 
Besides that, I'm interested in ways we can make coala more end-user friendly, as mentioned below, I think better plugin support would be a major step forward.

# Specific Responsibilities

I'm currently interested in the project of **better editor support** which involves implementing plugins for other editors and to have CI along with tests functioning. I've started some work on the coala plugin for VScode, and I'm also interested in solving the issues of the plugins which coala already has which don't get much attention as the main repo - including: coala-sublime. Other than that, I'm open to new possibilities :)

**Comment by adtac** [comment]
ack :)

**Comment by adtac** [comment]
@sils do you approve this application? (one more ack needed and you're the only other member)

**Comment by sils** [comment]
@RohanVB so I think the main problem with the plugins is one that you already pointed out:

> which don't get much attention as the main repo

all the plugins are so small and not regularly released. I think we need a sustainable solution to *all* plugins to make sure they work and they are released properly and regularly. I'm thinking we could move them into one repository with proper CI so when you change any plugin you also see if any other is broken. Also there should be release automation so we can release all plugins whenever we do a new coala release.

CC @Mixih about the release automation.

Would this be a direction that you'd be willing to drive forward as well?

**Comment by RohanVB** [comment]
I'm interested in the end user reception of coala and the issues linked with it. Since editor plugins is an important aspect of it, I'm willing to contribute to getting all the plugins in a single repo (attracting more contributors and making things more manageable); and hence maintaining them from that point. We could have proper documentation to go along with it so that it'll be easier to make future plugins. As a member, I'm willing to do this with guidance and a proper structured layout of what needs to be done. Any additional plugin made in the process will be a bonus. 

> Would this be a direction that you'd be willing to drive forward as well?

Yes, the above mentioned is aligned with my interests.

**Comment by sils** [comment]
ack, sounds gorgeous!

**Comment by sils** [comment]
@RohanVB can you give me an email address and make a PR adding yourself to the team in the repo? This should also close the issue
