### ISSUE TITLE
Core team member application: Asnel Christian

### ISSUE THREAD

**Issue by AsnelChristian** [coala/teams#47]
# Bio

I am Asnel Christian Ngoulla, a computer science undergraduate student from Cameroon.
I love python, java, machine learning and computer graphics. I am not funny... but i like hanging around with people who are ( ;) like @adtac, @Adrianzatreanu ... :sweat_smile: ).

# coala Contributions so far

I have contributed some codes to coala, coala-bears and coala-utils, and must of what i did had to do with settings, bears and Requirements...

# Road to the Future

Many things can still be done on the core, particularly improving on the efficiency of coala, and as a member to this team i am looking forward to do that.

**Comment by adtac** [comment]
ack, welcome @Asnelchristian :)

**Comment by adtac** [comment]
@sils do you approve this application? (one more ack needed and you're the only other member)

**Comment by sils** [comment]
@Asnelchristian so you would concretely try to work on the performance? Any specific points where you would like to optimize?

**Comment by sils** [comment]
ack

**Comment by adtac** [comment]
Merged
