### ISSUE TITLE
Core Team Member Application: Hemang Kumar

### ISSUE THREAD

**Issue by hemangsk** [coala/teams#48]
# Bio
I am Hemang, I'm a Computer Science and Engineering undergrad, I like programming in Python, JavaScript and I also love making Android & Web projects. I like to learn new stuff everyday and to share my knowledge whenever I can.

# coala Contributions so far

I've contributed to coala and coala-landing. I'm also working on adding a cool feature in coala-quickstart which will help in detecting files without extensions.

# Road to the Future

With increase in the usability factor of supporting tools like coala-quickstart, coala-docs, site and coala-html, we can help coala-users to get started easily. 
As a coala-dev I can and I should be able to find my way through the nitty gritties of usability but if we can make the use of quickstart tools more prevalent, a first time coala user will also be able to figure out their way very easily, and then they can dive deeper and start getting the hang of it.

# Specific Responsibilities

Apart from _I'm always up for all kinds of stuff_, I'd really like to work on enhancement of area of quick-start and coala sub-tools like coala-quickstart, coala-html.

**Comment by adtac** [comment]
ack :)

>I'd really like to work on enhancement of area of quick-start and coala sub-tools like coala-quickstart, coala-html

Brilliant :) They could really use some development. Plus you're pretty good with front-end, so you can probably improve coala-html a lot :)

**Comment by adtac** [comment]
@sils do you approve this application? (one more ack needed and you're the only other member)

**Comment by sils** [comment]
ack

**Comment by Mariatta** [comment]
ack

**Comment by adtac** [comment]
Merged
