### ISSUE TITLE
Aspects Team Member Application: Abinash Senapati

### ISSUE THREAD

**Issue by techievena** [coala/teams#54]
# Bio

My name is Abinash Senapati. I am currently pursuing my B.Tech. in Electronics and Electrical Communication Engineering at IIT Kharagpur, India. I am a 19 year old open-source enthusiast (well both software and hardware :wink:) 

# coala Contributions so far

My all merged commits are in coala/bears repo till now. I have been a regular reviewer of core and bears repo. I have also successfully committed a few changes in `apertium-lint` (linter for Apertium) to make it usable for writing bears in coala, and ApertiumLintBear is waiting for Apertium guys to release a new version of apertium-lint. Besides that, I have written the `MavenRequirement.py` in coala/package_manager (Gitlab) and I also have created a NuGet package for `llvm 3.4` for the use of coala.

# Road to the Future

I believe the success of a project is not defined by the complexity involved in its code-base but by the simplicity and utility of the software from the users' perspective. Currently coala works more or less as an integration platform for the code-analysis and the linting softwares; because as described in cEP-0005, for an user to run a certain bear, he/she must have previous knowledge about the software used in that bear.

Also we are not that visible to our users; as in case of newcomers and professionals, majority of the development and coding goes on in editors and compilers. Only devs love vim and nano. Our presence is not that significant in between the coders who would rely upon previously written bears.

Thus improvement of aspects and plug-ins is very essential for the growth of coala. As I have already ran coala over an existing project (`apertium-lint`), I know how miserable it can get when so much amount of unorganized results is thrown at your face(I mean fixing indentation in a py code is much important than displaying spacing inconsistency). Also I realised that writing a coafile was really a herculean task and therefore had to copy coafile from coala-repo. I plan to work on improving aspectclasses of coala. I think the first step to this is by mapping `CAN_DETECT` and `CAN_FIX` fields of bears with current aspects. I had done a bit of analysis and found that for a single language and a single kind of aspect, there are multiple bears. Therefore a default priority has to be set for a certain aspect i.e., for which bear to use, which can be further modified by user by defining his/her taste (We do not intend to show our users the bears until he/she wishes to see it). We also have to take care of current developments going on - __next-gen bears__. The design of the aspectclasses has to be such that it remains modular and extendable, independent of the other changes going on now or in future. The results must be organized and users must be given an option to view a certain kind of errors they want to view at a time, rather than messing it up. Also redundant result displaying must be removed (Result of E501 of PycodestyleBear is same as that of LineLengthBear).

# Specific Responsibilities

Our users are as important to us as our contributors. I therefore plan to work on developing this aspect of coala, where users can use rely upon coala as their code-analysis software without having knowledge of its internal bears. With Aspects team first I would work on implementing aspects support in coala and converting bears into aspects.

Besides that I'll constantly review codes in coala repos and help the newcomers fix their issues if they ask for help in gitter channel, to reduce the workload on maintainers.

**Comment by Techievena** [comment]
I am 19 till March 16. I wish this issue to be closed before that date. I am too lazy to change it to 20. :wink:

**Comment by techievena** [comment]
CC @sils @userzimmermann

**Comment by sils** [comment]
ack from me!

**Comment by userzimmermann** [comment]
Welcome to the aspects team, @Techievena :)

**Comment by techievena** [comment]
You just saved me by 30 minutes from editing my age in the issue. :laughing:
