### ISSUE TITLE
Aspects Team Member Application: Pratyush Prakash

### ISSUE THREAD

**Issue by pratyushprakash** [coala/teams#56]
# Bio

My name is Pratyush Prakash and I am studying Information Technology at NITK, Surathkal. I am 19 years old and technology is my passion. I <3 everything sci-fi and Formula 1. 

# coala Contributions so far

My main contributions have been at coala core. I have already solved two issues related to cEP-0005. Apart from this I have also solved various other issues and have even written a Bear (PyromaBear). Apart from writing code I have of course done reviews and helped newcomers out on the gitter channel. 

# Road to the Future

I wish to have aspects implemented in every bear and for the new configuration format involving tastes and aspects to be the De-facto method of configuring coala. The end goal is to have coala available and accessible to all, not only devs. I feel this is the first step towards making coala more accessible as it avoids the hassle of getting to know the bears. The users should be abstracted from the bears as it is not very intuitive to find every setting. Another functionality would be to be able to group results based on what aspects they analyze. It would make the work of future bear writers easier, if there are already bears which provide the same functionality. Eventually this will help coala take take over the world. 

# Specific Responsibilities

The first step would be to implement aspect support in coala. I would also like to assist in converting the bears to the aspect model. Apart from this I would be continuously adding new aspects and corresponding tastes for the bear writers to use.

**Comment by pratyushprakash** [comment]
CC @sils @userzimmermann

**Comment by sils** [comment]
Hey, will you help us with this independent of your GSoC? (IIUC you're applying?) I don't think it's wise to accept "conditional team memberships".

**Comment by pratyushprakash** [comment]
@sils No, this is not a conditional Application. I will be contributing independent of GSoC.

**Comment by userzimmermann** [comment]
Welcome to the team @pratyushprakash :)

**Comment by userzimmermann** [comment]
@pratyushprakash Please join https://gitter.im/coala/aspects
