### ISSUE TITLE
Core Team Application: Alexandru Maxim

### ISSUE THREAD

**Issue by Nosferatul** [coala/teams#57]
# Bio

Who are you? What makes you special?

I'm Alex, student at Politehnica(Bucharest) in 2nd year and I like challenges!

# coala Contributions so far

What contributions, coding or not, have you done to coala?

Pull requests for coala and coala-bears repo. I helped newcomers and reviewed pull requests. So far I like it and I want to keep going.

# Road to the Future

How do you plan to take forward coala as a team leader/member of your team? What changes will you make happen.

I want to help where I can and more code in the future! I'm very familiar  with the core code. Most of my prs are in coala repo. We should work on performance bottlenecks that can be 
improved and adds new functionality. Let's make coala even greater!

# Specific Responsibilities

What do you want to work on. Do you have worked out project ideas?
What do you want take responsibility for?

Anything. I think that I have enough experience to solve problems encountered.

**Comment by adtac** [comment]
Hey @Nosferatul can you make a PR adding yourself to the team members list directly?

**Comment by Nosferatul** [comment]
Done @adtac
