### ISSUE TITLE
Come aboard the bearship

### ISSUE THREAD

**Issue by userzimmermann** [coala/teams#63]
Or in other words: Let's create the **bearship crew** as new team :)

For further developing https://github.com/coala/bearsh and https://github.com/coala/bearship

@sils @sims1253 Opinions?
@yash-nisar You promised to join ;)
@coala/aspects-developers Anyone interested?
@MariosPanag Follow your captain ;)

**Comment by techievena** [comment]
I'm in :smile:

**Comment by yash-nisar** [comment]
Consider me in. :wink:

**Comment by AsnelChristian** [comment]
'yoyoyoyoyoyo' i am in

**Comment by meetmangukiya** [comment]
Me as well, it is the debugger thing, right?

**Comment by userzimmermann** [comment]
@meetmangukiya It's the `bearsh` extension for IPython for interactive bear/aspect running/debugging and the fancy `bearship` interface for Jupyter with custom theming, `bearsh` integration with visual extensions... and everything awesome we can imageine ;)

**Comment by rajendraarora16** [comment]
I am in. :)

**Comment by Makman2** [comment]
@userzimmermann what's actually the state of bearship?

**Comment by Makman2** [comment]
Seems it's quite stale here, if you want to have this team, please reopen :smile:
