### ISSUE TITLE
Core Team Member Application: Palash Nigam

### ISSUE THREAD

**Issue by palash25** [coala/teams#69]
# Bio
Hi, I'm Palash, a CS undergrad from India. I'm an open source enthusiast and a python fanboy. I am interested in distributed systems, blockchain and backend dev. I have recently gotten interested in the Nextgen core and caching.

# coala Contributions so far
Apart from raising lots of issues, giving reviews and helping out newcomers till now I have made 9 PRs (2 mediums and rest lows). I have also made a PR [documenting the Nextgen Core](https://github.com/coala/coala/pull/5262). I have also worked a little on the Globbing module.
 
# Road to the Future

I got interested in caching and the Nextgen core while selecting projects for GSoC and chose optimize caching as my project. Even if I don’t get selected I would love to work on this project, on coala in general and also on the Nextgen Core integration. I’m here to stay for the long run.

I have finnaly found my interest i.e. the Nextgen core and would like to work on its full integration and performance optimization. I would also like to work with @Makman2 on writing a [Mesos Scheduler](https://github.com/coala/coala/issues/4604) for coala since I recently got interested in distributed systems and asynchronous programming.

# Specific Responsibilities

One project I found interesting, but wasn't able to give much time to was *Integrating a debugger and profiler in coala*. If no one is selected for this GSoC project I would like to start working on it. At least do the research and maybe help someone else out who wants to work on it.

Besides that I would like to solve as many issues related to `area/core`, `type/performance` and `Nextgen-Core`. I also like to write docs and would love to contribute in that area too.

cc @adtac

**Comment by Makman2** [comment]
You're accepted from my side, but I'm not the team leader officially (yet), and I'm not sure if it's bureaucratically  correct if I accept your application by myself.

**Comment by Makman2** [comment]
But you can remove also the colon in the issue reference inside the commit message :3

**Comment by palash25** [comment]
> But you can remove also the colon in the issue reference inside the commit message :3

I hate it. I don't know why I made a habit out of this.

> You're accepted from my side, but I'm not the team leader officially (yet), and I'm not sure if it's bureaucratically correct if I accept your application by myself.

Thanks it means a lot coming from you.

**Comment by adtac** [comment]
@Makman2 do you want to be the team leader? I'm not doing much anyway, so it makes sense to have someone more involved IMO.

+1 from me too :)

**Comment by adtac** [comment]
@palash25 good choice of music, btw :)

**Comment by Makman2** [comment]
@adtac yeah I think would be beneficial if I'm taking on the leadership position :)
