### ISSUE TITLE
Add CoC to gsoc_responsibilities.md

### ISSUE THREAD

**Issue by jayvdb** [coala/teams#75]
`gsoc_responsibilities.md` should link to coala's [CoC](http://coala.io/coc)

**Comment by chhabrabhishek** [comment]
I want this issue to be assigned to me!@jayvdb

**Comment by chhabrabhishek** [comment]
@jayvdb hi! just tell me a single thing where do i have to give the link of coc in gsoc_responsibilities.md , i mean after which point or points
or do i make a seperate section?
