### ISSUE TITLE
Core Team Member Application: Abhinav Kaushlya

### ISSUE THREAD

**Issue by abhishalya** [coala/teams#81]
# Bio

>Who are you? What makes you special?

I'm Abhinav Kaushlya. I'm currently 14 years old and was a GCI student here at coala. I have worked on various coala issues during that time and before. I'm interested in 'learning through coala' as @jayvdb suggested.

# coala Contributions so far

>What contributions, coding or not, have you done to coala?

I have worked on several issue on coala, coala-bears, coAST and corobo, all coding related.

# Road to the Future

>How do you plan to take forward coala as a team leader/member of your team? What changes will you make happen.

I would definitely keep solving the issues, I'm also interested in some of the GSoC projects which I will be closely following and make few contributions there too.

# Specific Responsibilities

>What do you want to work on. Do you have worked out project ideas?

Yes, the current projects are nice and interesting. I would like to work on them if provided the opportunity. Since I think they are mostly for GSoC, I don't know if I'm allowed to work on any of them.

What do you want take responsibility for?

I would like to keep helping newcomers and reviewing their PRs and clear their doubts if any. As a core developer I would like to keep working on the issues and some of the projects.

cc @jayvdb @Makman2

**Comment by Makman2** [comment]
Approved ;)

@abhishalya Could you push a PR modifying the core team list?

**Comment by abhishalya** [comment]
Yay! Thank you @Makman2 
I have created the pull request https://github.com/coala/teams/pull/83
